### ISSUE TITLE
Am I calling the function correctly?

### ISSUE THREAD

**Issue by hrtgithub** [ganlbarone/FV2Keys#2]
PS C:\windows\system32> powershell -command "& { . C:\Users\user\Desktop\CasperFileVault.ps1; CasperFVault }"
Error Grabbing FileVault Key - The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel..

**Comment by ganlbarone** [comment]
Sorry for the super late reply on this. Not sure if you even still need this or not, but that ssl error should be fixed by hard setting tls1.2 I updated the function code so that it prefers tls 1.2 when you call it. Should work for you now.

**Comment by ganlbarone** [comment]
Please open a new case if you have additional problems. Thanks!
